trigger:
- master

pool:
  vmImage: vs2017-win2016

steps:
- powershell: (new-object System.Net.WebClient).DownloadFile('https://packages.chef.io/files/stable/chef-workstation/0.4.1/windows/2012/chef-workstation-0.4.1-1-x64.msi','C:\chef-workstation.msi')
  displayName: 'Download Chef Workstation'

- script: start /wait msiexec /i c:\chef-workstation.msi /qn
  displayName: 'Install Chef Workstation'
